version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: izi-app-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    # volumes:
    #   - $HOME/dataset/payment/postgres:/var/lib/postgresql/data
    networks:
      - database-net

  backend:
    build: ./api
    container_name: izi-app-api
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 50s -wait-retry-interval 10s ./docker-entrypoint.sh
    command: pm2-runtime dist/server.js --name izi_app_api
    # ports:
    #   - 3333:3333
    env_file:
      - ./api/.env
    # volumes:
    #   - ./api:/home/node/api
    depends_on:
      - postgres
    networks:
      - database-net
      - proxy-net

  nginx:
    container_name: izi-app-nginx
    build: ./nginx
    entrypoint: dockerize -wait http://backend:3333 -timeout 80s -wait-retry-interval 10s /docker-entrypoint.sh nginx -g 'daemon off;'
    # volumes:
    #   - ./nginx/conf/:/etc/nginx/conf.d/:rw
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    networks:
      - proxy-net

networks:
  database-net:
    driver: bridge
  proxy-net:
    driver: bridge