name: ci-main-build-workflow
on: 
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./api

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: Update API
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: "., !node_modules"
          target: "~/app/desafio-izi-app"

      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          script: |
            cd ~/app/desafio-izi-app
            yarn
            typeorm:run
            pm2 restart izi_app_api
